version: "3"
services:
  server:
    build: ./server
    ports:
      - 13000:3001
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1919
      DB_NAME: db-inrae

  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
      
volumes:
  postgres_data:
