version: "3.8"
services:
  client:
    container_name: frontend
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - network
    volumes:
      - shared-files:/usr/src/app/files

  server:
    container_name: api
    restart: always
    build: ./server
    ports:
      - 3001:3001
    networks:
      - network
    volumes:
      - shared-files:/usr/src/app/files

networks:
  network:
    driver: bridge

volumes:
  shared-files:
