version: "3.8"
services:
  client:
    container_name: frontend
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - network

  server:
    container_name: api
    restart: always
    build: ./server
    ports:
      - 13000:3001
    networks:
      - network

networks:
  network:
    driver: bridge
